export const CREATE_COURSE = "CREATE_COURSE_SUCCESS";
export const LOAD_SUCCESS = "LOAD_COURSE_SUCCESS";
export const AUTHOR_SUCCESS = "AUTHOR_COURSE_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const SAVE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
